import { Geist, Geist_Mono, Tangerine ,Pacifico } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const tangerine = Tangerine({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-tangerine",
});
const pacifico = Pacifico({
  subsets: ['latin'],
  weight: '400',
  variable: "--font-pacifico",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${tangerine.variable} ${pacifico.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <div className="bg-indigo-950 text-white flex flex-col justify-center items-center">
          <p>© 2026 VayuSoftwares. All Rights Reserved.</p>
          <p>software development company</p>
          <p>Harendrasinh: +91-986-777-5626</p>
        </div>
      </body>
    </html>
  );
}
